apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: venk-rancher
  namespace: docker-registry
spec:
  secretName: venk-rancher
  dnsNames:
  - venk-rancher.southeastasia.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - venk-rancher.southeastasia.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer