apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: ishi@ishirock.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}