apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: node-catalog-tls-secret
spec:
  secretName: node-catalog-tls-secret
  dnsNames:
  - node-catalog.ishirock.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - node-catalog.ishirock.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer