apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: ishirock
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ishi@ishirock.com
    privateKeySecretRef:
      name: ishirock
    http01: {}